apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo-service
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-demo
  ports:
  - protocol: TCP
    port: 80       # Port that the service is available on
    targetPort: 8081 # Port the container is listening on
